# -*- coding: utf-8 -*-
"""TransAttUNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmhjUJItwtZQOn1XupsY2wBJmm6-Jjjg
"""

# ===================== TransAttUNet import =====================
# 너의 폴더 구조에 맞게 경로만 맞춰주면 됨.
# 예: ./TransAttUnet/model/TransAttUnet.py 라면 아래처럼.
import sys
sys.path.insert(0, './TransAttUnet')  # ✅ 필요시 경로 수정

try:
    from model.TransAttUnet import UNet_Attention_Transformer_Multiscale
    print("✓ TransAttUNet imported successfully")
except Exception as e:
    print(f"⚠️ TransAttUNet import failed: {e}")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torch.nn.functional as F
import torch.backends.cudnn as cudnn

import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import time
import cv2
import os
import glob
import json
from dataclasses import dataclass, asdict
from typing import List, Tuple, Optional
from copy import deepcopy

import math

import segmentation_models_pytorch as smp
from sklearn.model_selection import StratifiedKFold
from scipy import ndimage

# Albumentations
from albumentations import (
    HorizontalFlip, ShiftScaleRotate, Normalize, Resize, Compose,
    RandomBrightnessContrast, RandomGamma, ElasticTransform,
    GridDistortion, OpticalDistortion
)

try:
    from albumentations.pytorch import ToTensorV2
    ToTensorTransform = ToTensorV2
except ImportError:
    try:
        from albumentations.torch import ToTensor
        ToTensorTransform = ToTensor
    except ImportError:
        class ToTensorTransform:
            def __call__(self, **kwargs):
                image = kwargs['image']
                mask = kwargs['mask']

                if len(image.shape) == 3:
                    image = image.transpose(2, 0, 1)

                image = torch.from_numpy(image).float()
                mask = torch.from_numpy(mask).unsqueeze(0).float()

                return {'image': image, 'mask': mask}

warnings.filterwarnings('ignore')

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA version:", torch.version.cuda)

@dataclass
class Config:
    experiment_name: str = "baseline"
    data_path: Path = Path('./siim_dataset/train_png')
    test_path: Path = Path('./siim_dataset/test_png')
    rle_path: Path = Path('./siim_dataset/train-rle.csv')
    base_save_dir: Path = Path('./ablation_results')

    # Data Sampling - positive_ratio로 변경
    use_dynamic_sampling: bool = False
    initial_positive_ratio: float = 0.8  # 수정
    final_positive_ratio: float = 0.4    # 수정

    # Augmentation
    use_heavy_augmentation: bool = False

    model_architecture: str = "TransUNet"
    backbone: str = "resnet34"

    #transUnet
    vit_name: str = "R50-ViT-B_16"
    vit_patches_size: int = 16
    n_skip: int = 3

    #early stop
    use_early_stopping: bool = True
    early_stopping_patience: int = 10
    early_stopping_metric: str = 'dice'
    early_stopping_min_delta: float = 0.0001

    # Loss
    use_combo_loss: bool = False
    bce_weight: float = 1.0
    dice_weight: float = 1.0
    focal_weight: float = 1.0
    focal_alpha: float = 10.0
    focal_gamma: float = 2.0

    # Post-processing
    use_triplet_threshold: bool = False
    triplet_top: float = 0.75
    triplet_bottom: float = 0.3
    triplet_min_area: int = 2000

    # Progressive Training
    use_progressive_training: bool = False
    warmup_epochs: int = 10
    high_sr_epochs: int = 10
    low_sr_epochs: int = 10
    final_epochs: int = 10

    # Progressive Resolution
    use_progressive_resolution: bool = False
    initial_size: int = 512
    final_size: int = 1024
    freeze_encoder_epochs: int = 5

    train_size: int = 512
    original_size: int = 1024

    # Training params
    fold: int = 0
    total_folds: int = 5
    batch_size: int = 4
    accumulation_steps: int = 8
    num_epochs: int = 40
    base_lr: float = 1e-4
    scheduler_type: str = "ReduceLROnPlateau"
    scheduler_patience: int = 3
    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'

    # Image params
    image_size: int = 512
    mean: Tuple[float, float, float] = (0.485, 0.456, 0.406)
    std: Tuple[float, float, float] = (0.229, 0.224, 0.225)

    num_workers: int = 0

    def __post_init__(self):
        if self.use_progressive_training:
            self.num_epochs = (self.warmup_epochs + self.high_sr_epochs +
                             self.low_sr_epochs + self.final_epochs)

        self._save_dir = Path(self.base_save_dir) / self.experiment_name
        self._save_dir.mkdir(exist_ok=True, parents=True)

    @property
    def save_dir(self):
        if not hasattr(self, '_save_dir'):
            self._save_dir = Path(self.base_save_dir) / self.experiment_name
            self._save_dir.mkdir(exist_ok=True, parents=True)
        return self._save_dir

    def get_current_positive_ratio(self, epoch):  # 수정
        if not self.use_dynamic_sampling:
            return self.initial_positive_ratio

        progress = epoch / max(1, self.num_epochs - 1)  # 수정
        ratio = self.initial_positive_ratio - (
            (self.initial_positive_ratio - self.final_positive_ratio) * progress
        )
        return max(min(ratio, 1.0), 0.0)  # 수정

    def get_current_image_size(self, epoch):
        return self.train_size

    def should_freeze_encoder(self, epoch):
        if not self.use_progressive_resolution:
            return False

        transition_epoch = self.num_epochs // 2
        return (epoch >= transition_epoch and
                epoch < transition_epoch + self.freeze_encoder_epochs)

    def get_lr_and_scheduler(self, epoch, optimizer):
        if not self.use_progressive_training:
            return self.base_lr, self.scheduler_type

        if epoch < self.warmup_epochs:
            lr = 1e-3
            scheduler_type = "ReduceLROnPlateau"
        elif epoch < self.warmup_epochs + self.high_sr_epochs:
            lr = 1e-5
            scheduler_type = "CosineAnnealingLR"
        elif epoch < self.warmup_epochs + self.high_sr_epochs + self.low_sr_epochs:
            lr = 1e-5
            scheduler_type = "CosineAnnealingLR"
        else:
            lr = 1e-6
            scheduler_type = "constant"

        for param_group in optimizer.param_groups:
            param_group['lr'] = lr

        return lr, scheduler_type

    def save(self):
        config_dict = {
            'experiment_name': self.experiment_name,
            'data_path': str(self.data_path),
            'test_path': str(self.test_path),
            'rle_path': str(self.rle_path),
            'base_save_dir': str(self.base_save_dir),
            'save_dir': str(self.save_dir),

            'use_dynamic_sampling': self.use_dynamic_sampling,
            'initial_positive_ratio': self.initial_positive_ratio,
            'final_positive_ratio': self.final_positive_ratio,

            'use_heavy_augmentation': self.use_heavy_augmentation,

            'use_combo_loss': self.use_combo_loss,
            'bce_weight': self.bce_weight,
            'dice_weight': self.dice_weight,
            'focal_weight': self.focal_weight,
            'focal_alpha': self.focal_alpha,
            'focal_gamma': self.focal_gamma,

            'use_triplet_threshold': self.use_triplet_threshold,
            'triplet_top': self.triplet_top,
            'triplet_bottom': self.triplet_bottom,
            'triplet_min_area': self.triplet_min_area,

            'use_progressive_training': self.use_progressive_training,
            'warmup_epochs': self.warmup_epochs,
            'high_sr_epochs': self.high_sr_epochs,
            'low_sr_epochs': self.low_sr_epochs,
            'final_epochs': self.final_epochs,

            'use_progressive_resolution': self.use_progressive_resolution,
            'initial_size': self.initial_size,
            'final_size': self.final_size,
            'freeze_encoder_epochs': self.freeze_encoder_epochs,

            'backbone': self.backbone,

            'fold': self.fold,
            'total_folds': self.total_folds,
            'batch_size': self.batch_size,
            'accumulation_steps': self.accumulation_steps,
            'num_epochs': self.num_epochs,
            'base_lr': self.base_lr,
            'scheduler_type': self.scheduler_type,
            'scheduler_patience': self.scheduler_patience,
            'device': self.device,

            'image_size': self.image_size,
            'mean': list(self.mean),
            'std': list(self.std),

            'num_workers': self.num_workers,
        }

        with open(self.save_dir / 'config.json', 'w') as f:
            json.dump(config_dict, f, indent=4)

def run_length_decode(rle, height=1024, width=1024, fill_value=1):
    """RLE 디코딩"""
    component = np.zeros((height, width), np.float32)
    component = component.reshape(-1)
    rle = np.array([int(s) for s in rle.strip().split(' ')])
    rle = rle.reshape(-1, 2)
    start = 0
    for index, length in rle:
        start = start+index
        end = start+length
        component[start: end] = fill_value
        start = end
    component = component.reshape(width, height).T
    return component

def run_length_encode(component):
    """RLE 인코딩"""
    component = component.T.flatten()
    start = np.where(component[1:] > component[:-1])[0]+1
    end = np.where(component[:-1] > component[1:])[0]+1
    length = end-start
    rle = []
    for i in range(len(length)):
        if i == 0:
            rle.extend([start[0], length[0]])
        else:
            rle.extend([start[i]-end[i-1], length[i]])
    rle = ' '.join([str(r) for r in rle])
    return rle

def build_filename_mapping(data_folder, additional_folder=None):
    """파일명 매핑 생성"""
    folders = [data_folder]
    if additional_folder:
        folders.append(additional_folder)

    mapping = {}
    for folder in folders:
        all_files = glob.glob(os.path.join(folder, "*.png"))

        for filepath in all_files:
            filename = os.path.basename(filepath)
            name_without_ext = filename.replace('.png', '')
            name_without_dcm = name_without_ext.replace('.dcm', '')

            mapping[name_without_ext] = filepath
            mapping[name_without_dcm] = filepath

    return mapping

def get_transforms(phase, size, mean, std, use_heavy_aug=False):
    """
    Transform 생성
    use_heavy_aug=True: 1등 솔루션의 heavy augmentation
    """
    list_transforms = []

    if phase == "train":
        list_transforms.append(HorizontalFlip(p=0.5))

        if use_heavy_aug:
            # 1등 솔루션의 augmentation
            list_transforms.extend([
                RandomBrightnessContrast(
                    brightness_limit=0.2,
                    contrast_limit=0.2,
                    p=0.3
                ),
                RandomGamma(gamma_limit=(80, 120), p=0.3),
                ElasticTransform(
                    alpha=1, sigma=50, alpha_affine=50, p=0.3
                ),
                GridDistortion(p=0.3),
                OpticalDistortion(distort_limit=0.05, shift_limit=0.05, p=0.3),
                ShiftScaleRotate(
                    shift_limit=0.1,
                    scale_limit=0.1,
                    rotate_limit=15,
                    border_mode=cv2.BORDER_CONSTANT,
                    p=0.5
                ),
            ])
        else:
            # Baseline augmentation
            list_transforms.append(
                ShiftScaleRotate(
                    shift_limit=0,
                    scale_limit=0.1,
                    rotate_limit=10,
                    p=0.5,
                    border_mode=cv2.BORDER_CONSTANT
                )
            )

    list_transforms.extend([
        Resize(size, size),
        Normalize(mean=mean, std=std, p=1),
        ToTensorTransform(),
    ])

    return Compose(list_transforms)

class SIIMDataset(Dataset):
    def __init__(self, df, fnames, data_folder, size, mean, std, phase,
                 test_data_folder=None, use_heavy_aug=False):
        self.df = df
        self.root = data_folder
        self.size = size
        self.mean = mean
        self.std = std
        self.phase = phase
        self.transforms = get_transforms(phase, size, mean, std, use_heavy_aug)
        self.gb = self.df.groupby('ImageId')
        self.fnames = fnames
        self.indices = np.arange(len(self.fnames))

        # 파일명 매핑
        self.file_mapping = build_filename_mapping(data_folder, test_data_folder)

        self.mask_area_cache = []
        for image_id in self.fnames:
            df = self.gb.get_group(image_id)
            annotations = df[' EncodedPixels'].tolist()

            if annotations[0] == ' -1':
                area = 0
            else:
                mask = np.zeros([1024,1024], dtype=np.float32)
                for rle in annotations:
                    decoded = run_length_decode(rle)
                    decoded = decoded.astype(np.float32)
                    mask += decoded
                area = mask.sum()

            self.mask_area_cache.append(area)

    def __getitem__(self, idx):
        image_id = self.fnames[idx]
        df = self.gb.get_group(image_id)
        annotations = df[' EncodedPixels'].tolist()

        # 파일 경로
        if image_id not in self.file_mapping:
            raise FileNotFoundError(f"ImageId not in mapping: {image_id}")

        image_path = self.file_mapping[image_id]

        # 이미지 읽기
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError(f"Failed to read: {image_path}")

        # 마스크 생성
        mask = np.zeros([1024, 1024], dtype=np.float32)
        if annotations[0] != ' -1':
            for rle in annotations:
                mask += run_length_decode(rle)
        mask = (mask >= 1).astype('float32')

        # Transform
        augmented = self.transforms(image=image, mask=mask)
        image = augmented['image']
        mask = augmented['mask']

        if len(mask.shape) == 2:
            mask = mask.unsqueeze(0)

        return image, mask

    def __len__(self):
        return len(self.fnames)

def provider(
    fold,
    total_folds,
    data_folder,
    df_path,
    phase,
    size,
    mean=None,
    std=None,
    batch_size=8,
    num_workers=0,
    test_data_folder=None,
    positive_ratio=0.8,
    use_heavy_aug=False,
):
    """
    DataLoader 생성
    positive_ratio: 전체 샘플 중 positive 샘플의 비율
    """
    df_all = pd.read_csv(df_path)
    df = df_all.drop_duplicates('ImageId')

    # Sampling
    df_with_mask = df[df[" EncodedPixels"] != " -1"]
    df_without_mask = df[df[" EncodedPixels"] == " -1"]

    n_positive = len(df_with_mask)
    n_negative = int(n_positive * (1 - positive_ratio) / positive_ratio)  # 수정

    df_without_mask_sampled = df_without_mask.sample(
        min(n_negative, len(df_without_mask)),
        random_state=69
    )
    df = pd.concat([df_with_mask, df_without_mask_sampled])
    df['has_mask'] = (df[" EncodedPixels"] != " -1").astype(int)

    # K-Fold split
    kfold = StratifiedKFold(total_folds, shuffle=True, random_state=69)
    train_idx, val_idx = list(kfold.split(df["ImageId"], df["has_mask"]))[fold]
    train_df, val_df = df.iloc[train_idx], df.iloc[val_idx]
    df = train_df if phase == "train" else val_df

    fnames = df['ImageId'].values

    image_dataset = SIIMDataset(
        df_all, fnames, data_folder, size, mean, std, phase,
        test_data_folder=test_data_folder,
        use_heavy_aug=use_heavy_aug
    )

    dataloader = DataLoader(
        image_dataset,
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=True,
        shuffle=(phase == "train"),
    )
    return dataloader

def dice_loss(input, target):
    """Dice Loss"""
    input = torch.sigmoid(input)
    smooth = 1.0
    iflat = input.view(-1)
    tflat = target.view(-1)
    intersection = (iflat * tflat).sum()
    return ((2.0 * intersection + smooth) / (iflat.sum() + tflat.sum() + smooth))

class FocalLoss(nn.Module):
    """Focal Loss"""
    def __init__(self, gamma):
        super().__init__()
        self.gamma = gamma

    def forward(self, input, target):
        if not (target.size() == input.size()):
            raise ValueError("Target size must be the same as input size")
        max_val = (-input).clamp(min=0)
        loss = input - input * target + max_val + \
            ((-max_val).exp() + (-input - max_val).exp()).log()
        invprobs = F.logsigmoid(-input * (target * 2.0 - 1.0))
        loss = (invprobs * self.gamma).exp() * loss
        return loss.mean()


class MixedLoss(nn.Module):
    """Baseline Mixed Loss"""
    def __init__(self, alpha, gamma):
        super().__init__()
        self.alpha = alpha
        self.focal = FocalLoss(gamma)

    def forward(self, input, target):
        loss = self.alpha*self.focal(input, target) - torch.log(dice_loss(input, target))
        return loss.mean()


class ComboLoss(nn.Module):
    """
    1등 솔루션의 Combo Loss
    BCE + Dice + Focal의 가중 조합
    """
    def __init__(self, bce_weight=1.0, dice_weight=1.0, focal_weight=1.0,
                 focal_alpha=10.0, focal_gamma=2.0):
        super().__init__()
        self.bce_weight = bce_weight
        self.dice_weight = dice_weight
        self.focal_weight = focal_weight

        self.bce = nn.BCEWithLogitsLoss()
        self.focal = FocalLoss(focal_gamma)
        self.focal_alpha = focal_alpha

    def forward(self, input, target):
        bce = self.bce(input, target)
        dice = 1 - dice_loss(input, target)
        focal = self.focal(input, target)

        loss = (self.bce_weight * bce +
                self.dice_weight * dice +
                self.focal_weight * focal)

        return loss



def triplet_threshold_post_process(prob, top_th=0.75, bottom_th=0.3, min_area=2000):
    """
    1등 솔루션의 Triplet Threshold Post-processing

    Args:
        prob: Probability map (H, W)
        top_th: 상위 threshold (seed 찾기)
        bottom_th: 하위 threshold (확장)
        min_area: 최소 영역 크기

    Returns:
        Binary mask
    """
    # 전체 마스크가 없으면 empty 반환
    if prob.max() < top_th:
        return np.zeros_like(prob)

    # Top threshold로 seed 찾기
    seeds = prob > top_th

    # Bottom threshold로 확장할 영역 정의
    expansion_mask = prob > bottom_th

    # Connected components on seeds
    labeled, num_features = ndimage.label(seeds)

    final_mask = np.zeros_like(prob)

    for i in range(1, num_features + 1):
        component = (labeled == i)

        # Seed에서 시작해서 bottom threshold 영역으로 확장
        expanded = ndimage.binary_dilation(
            component,
            iterations=20,  # 충분히 확장
            mask=expansion_mask
        )

        # 크기 필터링
        if expanded.sum() >= min_area:
            final_mask = np.maximum(final_mask, expanded.astype(float))

    return final_mask


def apply_post_processing(probs, config):
    """
    Batch에 post-processing 적용

    Args:
        probs: (B, 1, H, W) tensor
        config: AblationConfig

    Returns:
        Processed predictions (B, 1, H, W)
    """
    if not config.use_triplet_threshold:
        return (probs > 0.5).float()

    batch_size = probs.shape[0]
    processed = torch.zeros_like(probs)

    for i in range(batch_size):
        prob = probs[i, 0].cpu().numpy()

        mask = triplet_threshold_post_process(
            prob,
            top_th=config.triplet_top,
            bottom_th=config.triplet_bottom,
            min_area=config.triplet_min_area
        )

        processed[i, 0] = torch.from_numpy(mask).float()

    return processed

def predict(X, threshold):
    """Prediction with threshold"""
    X_p = np.copy(X)
    preds = (X_p > threshold).astype('uint8')
    return preds

def metric(probability, truth, threshold=0.5, reduction='none'):
    batch_size = len(truth)
    with torch.no_grad():
        probability = probability.view(batch_size, -1)
        truth = truth.view(batch_size, -1)
        assert(probability.shape == truth.shape)

        p = (probability > threshold).float()
        t = (truth > 0.5).float()

        t_sum = t.sum(-1)
        p_sum = p.sum(-1)

        neg_index = torch.nonzero(t_sum == 0).squeeze(1)
        pos_index = torch.nonzero(t_sum >= 1).squeeze(1)

        dice_neg = (p_sum == 0).float()
        dice_pos = 2 * (p*t).sum(-1)/((p+t).sum(-1))

        dice_neg = dice_neg[neg_index]
        dice_pos = dice_pos[pos_index]
        dice = torch.cat([dice_pos, dice_neg])

        num_neg = len(neg_index)
        num_pos = len(pos_index)

    return dice, dice_neg, dice_pos, num_neg, num_pos

def compute_ious(pred, label, classes, ignore_index=255, only_present=True):
    """IoU computation"""
    pred[label == ignore_index] = 0
    ious = []
    for c in classes:
        label_c = label == c
        if only_present and np.sum(label_c) == 0:
            ious.append(np.nan)
            continue
        pred_c = pred == c
        intersection = np.logical_and(pred_c, label_c).sum()
        union = np.logical_or(pred_c, label_c).sum()
        if union != 0:
            ious.append(intersection / union)
    return ious if ious else [1]


def compute_iou_batch(outputs, labels, classes=None):
    """IoU batch computation"""
    ious = []
    preds = np.copy(outputs)
    labels = np.array(labels)
    for pred, label in zip(preds, labels):
        ious.append(np.nanmean(compute_ious(pred, label, classes)))
    iou = np.nanmean(ious)
    return iou

class Meter:
    """Metric meter"""
    def __init__(self, phase, epoch):
        self.base_threshold = 0.5
        self.base_dice_scores = []
        self.dice_neg_scores = []
        self.dice_pos_scores = []
        self.iou_scores = []

    def update(self, targets, outputs):
        probs = torch.sigmoid(outputs)
        dice, dice_neg, dice_pos, _, _ = metric(probs, targets, self.base_threshold)
        self.base_dice_scores.extend(dice.cpu().numpy() if torch.is_tensor(dice) else [dice])
        self.dice_pos_scores.extend(dice_pos.cpu().numpy() if len(dice_pos) > 0 else [])
        self.dice_neg_scores.extend(dice_neg.cpu().numpy() if len(dice_neg) > 0 else [])
        preds = predict(probs.cpu().numpy(), self.base_threshold)
        iou = compute_iou_batch(preds, targets.cpu().numpy(), classes=[1])
        self.iou_scores.append(iou)

    def get_metrics(self):
        dice = np.nanmean(self.base_dice_scores)
        dice_neg = np.nanmean(self.dice_neg_scores)
        dice_pos = np.nanmean(self.dice_pos_scores)
        dices = [dice, dice_neg, dice_pos]
        iou = np.nanmean(self.iou_scores)
        return dices, iou


def epoch_log(phase, epoch, epoch_loss, meter, start):
    """Epoch logging"""
    dices, iou = meter.get_metrics()
    dice, dice_neg, dice_pos = dices
    print("Loss: %0.4f | dice: %0.4f | dice_neg: %0.4f | dice_pos: %0.4f | IoU: %0.4f" %
          (epoch_loss, dice, dice_neg, dice_pos, iou))
    return dice, iou

def get_curriculum_indices(dataset, epoch, total_epochs):
    areas = np.array(dataset.mask_area_cache)  # dataset에 mask_area_cache가 미리 있어야 함
    # large -> small 으로 정렬 (내림차순)
    sorted_idx = np.argsort(-areas)
    return sorted_idx  # 전체 길이 반환

class Trainer:
    def __init__(self, model, config: Config):
        self.config = config
        self.fold = config.fold
        self.total_folds = config.total_folds
        self.num_workers = config.num_workers
        self.batch_size = {"train": config.batch_size, "val": config.batch_size}
        self.accumulation_steps = config.accumulation_steps
        self.num_epochs = config.num_epochs
        self.best_loss = float("inf")
        self.phases = ["train", "val"]
        self.device = torch.device(config.device)

        self.best_metric = None        # dice / iou / loss 등 기준 metric의 best 값
        self.early_stop_counter = 0    # 개선 없이 몇 epoch 갔는지 카운트
        self.best_ckpt_metric = None   # ✅ 체크포인트 저장 기준

        self.net = model

        # Loss function 선택
        if config.use_combo_loss:
            self.criterion = ComboLoss(
                bce_weight=config.bce_weight,
                dice_weight=config.dice_weight,
                focal_weight=config.focal_weight,
                focal_alpha=config.focal_alpha,
                focal_gamma=config.focal_gamma
            )
            print(f"✓ Using Combo Loss (BCE:{config.bce_weight}, Dice:{config.dice_weight}, Focal:{config.focal_weight})")
        else:
            self.criterion = MixedLoss(config.focal_alpha, config.focal_gamma)
            print(f"✓ Using Mixed Loss (Focal alpha={config.focal_alpha}, gamma={config.focal_gamma})")

        self.optimizer = optim.Adam(self.net.parameters(), lr=config.base_lr)

        # Scheduler
        if config.scheduler_type == "ReduceLROnPlateau":
            self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
                self.optimizer, mode="min", patience=config.scheduler_patience,
            )
        elif config.scheduler_type == "CosineAnnealingLR":
            self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
                self.optimizer, T_max=config.num_epochs
            )
        else:
            self.scheduler = None

        self.net = self.net.to(self.device)

        if torch.cuda.is_available():
            cudnn.benchmark = True

        # DataLoaders
        self.current_image_size = config.train_size
        self.current_positive_ratio = config.initial_positive_ratio  # 수정
        self._create_dataloaders()

        self.losses = {phase: [] for phase in self.phases}
        self.iou_scores = {phase: [] for phase in self.phases}
        self.dice_scores = {phase: [] for phase in self.phases}

    def _create_dataloaders(self):
        """DataLoader 생성"""
        self.dataloaders = {
            phase: provider(
                fold=self.fold,
                total_folds=self.total_folds,
                data_folder=str(self.config.data_path),
                df_path=str(self.config.rle_path),
                phase=phase,
                size=self.current_image_size,
                mean=self.config.mean,
                std=self.config.std,
                batch_size=self.batch_size[phase],
                num_workers=self.num_workers,
                test_data_folder=str(self.config.test_path),
                positive_ratio=self.current_positive_ratio,  # 수정
                use_heavy_aug=self.config.use_heavy_augmentation,
            )
            for phase in self.phases
        }

    def _update_epoch_settings(self, epoch):
        """Epoch마다 설정 업데이트"""
        updated = False

        # Progressive resolution 체크
        new_size = self.config.get_current_image_size(epoch)
        if new_size != self.current_image_size:
            print(f"\n{'='*80}")
            print(f"🔍 Resolution Change: {self.current_image_size} → {new_size}")
            print(f"{'='*80}")
            self.current_image_size = new_size
            updated = True

        # Dynamic sampling 체크
        new_ratio = self.config.get_current_positive_ratio(epoch)
        if abs(new_ratio - self.current_positive_ratio) > 0.01:
            print(f"\n{'='*80}")
            print(f"📊 Positive Sampling Ratio: {self.current_positive_ratio:.2f} → {new_ratio:.2f}")
            print(f"{'='*80}")
            self.current_positive_ratio = new_ratio
            updated = True

        # DataLoader 재생성
        if updated:
            self._create_dataloaders()

        # ============================================================
        # ✅ Encoder freeze/unfreeze — "encoder"가 있는 모델만 처리
        # ============================================================
        def _has_encoder(m):
            return hasattr(m, "encoder") and (m.encoder is not None)

        if self.config.should_freeze_encoder(epoch):
            if not hasattr(self, '_encoder_frozen') or not self._encoder_frozen:
                print(f"\n{'='*80}")
                print(f"🔒 Freezing Encoder (if available)")
                print(f"{'='*80}")

                if _has_encoder(self.net):
                    for param in self.net.encoder.parameters():
                        param.requires_grad = False
                    self._encoder_frozen = True
                else:
                    print("⚠️ This model has no .encoder attribute. Skipping freeze.")
                    self._encoder_frozen = True
        else:
            if hasattr(self, '_encoder_frozen') and self._encoder_frozen:
                print(f"\n{'='*80}")
                print(f"🔓 Unfreezing Encoder (if available)")
                print(f"{'='*80}")

                if _has_encoder(self.net):
                    for param in self.net.encoder.parameters():
                        param.requires_grad = True
                else:
                    print("⚠️ This model has no .encoder attribute. Skipping unfreeze.")
                self._encoder_frozen = False

        # ============================================================
        # Progressive training LR 업데이트
        # ============================================================
        if self.config.use_progressive_training:
            lr, scheduler_type = self.config.get_lr_and_scheduler(epoch, self.optimizer)

            if scheduler_type != self.config.scheduler_type:
                if scheduler_type == "CosineAnnealingLR":
                    remaining_epochs = self.num_epochs - epoch
                    self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
                        self.optimizer, T_max=remaining_epochs
                    )
                elif scheduler_type == "ReduceLROnPlateau":
                    self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
                        self.optimizer, mode="min", patience=3,
                    )
                else:
                    self.scheduler = None

                self.config.scheduler_type = scheduler_type
                print(f"📈 LR: {lr:.2e}, Scheduler: {scheduler_type}")


    def forward(self, images, targets):
        images = images.to(self.device)
        masks = targets.to(self.device)
        outputs = self.net(images)
        loss = self.criterion(outputs, masks)
        return loss, outputs

    def iterate(self, epoch, phase):
        meter = Meter(phase, epoch)
        start = time.strftime("%H:%M:%S")
        print(f"Starting epoch: {epoch} | phase: {phase} | ⏰: {start}")

        is_train = (phase == "train")
        batch_size = self.batch_size[phase]
        self.net.train(is_train)
        dataloader = self.dataloaders[phase]
        running_loss = 0.0
        total_batches = len(dataloader)

        if is_train:
            self.optimizer.zero_grad()

        tk0 = tqdm(dataloader, total=total_batches, desc=f"Epoch {epoch} [{phase}]")

        for itr, batch in enumerate(tk0):
            images, targets = batch

            if is_train:
                # ---- train: autograd ON + gradient accumulation ----
                loss, outputs = self.forward(images, targets)
                loss = loss / self.accumulation_steps
                loss.backward()

                if (itr + 1) % self.accumulation_steps == 0:
                    self.optimizer.step()
                    self.optimizer.zero_grad()

            else:
                # ---- val: autograd OFF (메모리 절약, OOM 방지) ----
                with torch.no_grad():
                    loss, outputs = self.forward(images, targets)

            running_loss += loss.item()

            # ---- Metric 계산 (1024로 복원) - train/val 공통 ----
            with torch.no_grad():
                outputs_resized = F.interpolate(
                    outputs.detach(),
                    size=(self.config.original_size, self.config.original_size),
                    mode='bilinear',
                    align_corners=False
                )
                targets_resized = F.interpolate(
                    targets.detach(),
                    size=(self.config.original_size, self.config.original_size),
                    mode='nearest'
                )

                outputs_resized = outputs_resized.cpu()
                targets_resized = targets_resized.cpu()
                meter.update(targets_resized, outputs_resized)

            tk0.set_postfix(loss=(running_loss / (itr + 1)))

        # ---- epoch loss 정리 ----
        if is_train:
            # train에서는 loss를 acc_steps로 나누고 누적했으므로 다시 곱해줌
            epoch_loss = (running_loss * self.accumulation_steps) / total_batches
        else:
            epoch_loss = running_loss / total_batches

        dice, iou = epoch_log(phase, epoch, epoch_loss, meter, start)

        self.losses[phase].append(epoch_loss)
        self.dice_scores[phase].append(dice)
        self.iou_scores[phase].append(iou)

        torch.cuda.empty_cache()
        return epoch_loss


    def start(self):

        for epoch in range(self.num_epochs):
            # 해상도 / positive_ratio / encoder freeze 등 epoch별 설정 업데이트
            self._update_epoch_settings(epoch)

            train_loss = self.iterate(epoch, "train")
            val_loss = self.iterate(epoch, "val")

            # 🔹 best_loss는 val_loss 기준으로 계속 갱신 (로그/요약용)
            if val_loss < self.best_loss:
                self.best_loss = val_loss

            # 체크포인트 저장용 state
            state = {
                "epoch": epoch,
                "best_loss": self.best_loss,
                "state_dict": self.net.state_dict(),
                "optimizer": self.optimizer.state_dict(),
            }

            # 🔹 스케줄러 업데이트
            if self.scheduler is not None:
                if isinstance(self.scheduler, optim.lr_scheduler.ReduceLROnPlateau):
                    self.scheduler.step(val_loss)
                else:
                    self.scheduler.step()

            # ============================================================
            # 🔥 체크포인트 저장 로직 — early_stopping_metric 기준(dice)
            # ============================================================
            metric_name = self.config.early_stopping_metric

            if metric_name == 'dice':
                current_ckpt_metric = self.dice_scores['val'][-1]  # 클수록 좋음
            elif metric_name == 'iou':
                current_ckpt_metric = self.iou_scores['val'][-1]
            elif metric_name == 'loss':
                current_ckpt_metric = -val_loss                   # 작을수록 좋으므로 부호 반전
            else:
                current_ckpt_metric = self.dice_scores['val'][-1]  # fallback

            if (self.best_ckpt_metric is None) or (current_ckpt_metric > self.best_ckpt_metric):
                self.best_ckpt_metric = current_ckpt_metric
                print("******** New optimal found, saving state ********")

                state["best_metric"] = self.best_ckpt_metric
                torch.save(state, str(self.config.save_dir / "model.pth"))


            # ============================================================
            # 🔥 Early Stopping 로직
            # ============================================================
            if self.config.use_early_stopping:
                metric_name = self.config.early_stopping_metric

                if metric_name == 'dice':
                    current_metric = self.dice_scores['val'][-1]
                    improved = (
                        self.best_metric is None
                        or current_metric - self.best_metric > self.config.early_stopping_min_delta
                    )

                elif metric_name == 'iou':
                    current_metric = self.iou_scores['val'][-1]
                    improved = (
                        self.best_metric is None
                        or current_metric - self.best_metric > self.config.early_stopping_min_delta
                    )

                elif metric_name == 'loss':
                    current_metric = val_loss
                    improved = (
                        self.best_metric is None
                        or self.best_metric - current_metric > self.config.early_stopping_min_delta
                    )

                else:
                    current_metric = self.dice_scores['val'][-1]
                    improved = (
                        self.best_metric is None
                        or current_metric - self.best_metric > self.config.early_stopping_min_delta
                    )

                # 기록 갱신
                if improved:
                    self.best_metric = current_metric
                    self.early_stop_counter = 0
                    print(f"[EarlyStopping] {metric_name} improved to {current_metric:.6f}")

                else:
                    self.early_stop_counter += 1
                    print(
                        f"[EarlyStopping] No improvement in {metric_name} "
                        f"for {self.early_stop_counter}/{self.config.early_stopping_patience} epochs"
                    )

                # patience 초과 → stop
                if self.early_stop_counter >= self.config.early_stopping_patience:
                    print(f"\n[EarlyStopping] Patience reached. Stopping at epoch {epoch}.")
                    break

            print()



def create_model(config: Config):
    print(f"Creating model with backbone: {config.backbone}")

    architecture = config.model_architecture if hasattr(config, 'model_architecture') else "Unet"

    try:
        if architecture == "Unet":
            model = smp.Unet(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        elif architecture == "TransUNet":
            vit_name = config.vit_name
            vit_config = CONFIGS_ViT_seg[vit_name]

            vit_config.n_classes = 1
            vit_config.n_skip = config.n_skip

            if vit_name.find('R50') != -1:
                vit_config.patches.grid = (
                    int(config.image_size / config.vit_patches_size),
                    int(config.image_size / config.vit_patches_size)
                )

            model = ViT_seg(
                vit_config,
                img_size=config.image_size,
                num_classes=vit_config.n_classes,
                vis=True
            )

            pretrained_path = "./TransUNet/pretrained_weights/R50-ViT-B_16.npz"
            if os.path.exists(pretrained_path):
                try:
                    model.load_from(weights=np.load(pretrained_path))
                    print(f"✓ Loaded pretrained weights from {pretrained_path}")
                except Exception as e:
                    print(f"⚠️ Failed to load pretrained weights: {e}")
                    print("⚠️ Using random initialization!")
            else:
                print(f"⚠️ Pretrained weights not found at {pretrained_path}")
                print("⚠️ Using random initialization!")

            print(f"✓ Created TransUNet-{vit_name}")

        # ===================== ✅ TransAttUNet 추가 =====================
        elif architecture == "TransAttUNet":
            # SIIMDataset: cv2.imread -> (H,W,3) BGR / Normalize(mean,std)
            # 마스크: 1채널이므로 n_classes=1
            model = UNet_Attention_Transformer_Multiscale(
                n_channels=3,
                n_classes=1,
                bilinear=True
            )
            print("✓ Created TransAttUNet (UNet_Attention_Transformer_Multiscale)")

        elif architecture == "UnetPlusPlus":
            model = smp.UnetPlusPlus(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        elif architecture == "FPN":
            model = smp.FPN(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        elif architecture == "PSPNet":
            model = smp.PSPNet(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        elif architecture == "DeepLabV3":
            model = smp.DeepLabV3(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        elif architecture == "DeepLabV3Plus":
            model = smp.DeepLabV3Plus(
                encoder_name=config.backbone,
                encoder_weights="imagenet",
                activation=None
            )
            print(f"✓ Created {architecture} with {config.backbone}")

        else:
            raise ValueError(f"Unknown architecture: {architecture}")

        return model

    except Exception as e:
        print(f"❌ Error creating model: {e}")
        import traceback
        traceback.print_exc()
        print(f"Falling back to resnet34 U-Net...")
        return smp.Unet("resnet34", encoder_weights="imagenet", activation=None)



def run_experiment(config: Config):
    """단일 실험 실행"""
    print("\n" + "="*80)
    print(f"EXPERIMENT: {config.experiment_name}")
    print("="*80)
    print(f"Device: {config.device}")
    print(f"Fold: {config.fold}/{config.total_folds}")
    print(f"Backbone: {config.backbone}")
    print(f"Image size: {config.image_size}")
    print(f"Batch size: {config.batch_size}")
    print(f"Accumulation steps: {config.accumulation_steps}")
    print(f"Effective batch: {config.batch_size * config.accumulation_steps}")
    print(f"Epochs: {config.num_epochs}")
    print("\n--- Ablation Settings ---")
    print(f"Dynamic Sampling: {config.use_dynamic_sampling}")
    if config.use_dynamic_sampling:
        print(f"  Initial positive ratio: {config.initial_positive_ratio}")  # 수정
        print(f"  Final positive ratio: {config.final_positive_ratio}")      # 수정
    print(f"Heavy Augmentation: {config.use_heavy_augmentation}")
    print(f"Combo Loss: {config.use_combo_loss}")
    if config.use_combo_loss:
        print(f"  Weights - BCE:{config.bce_weight}, Dice:{config.dice_weight}, Focal:{config.focal_weight}")
    print(f"Triplet Threshold: {config.use_triplet_threshold}")
    if config.use_triplet_threshold:
        print(f"  Top:{config.triplet_top}, Bottom:{config.triplet_bottom}, Min area:{config.triplet_min_area}")
    print(f"Progressive Training: {config.use_progressive_training}")
    print(f"Progressive Resolution: {config.use_progressive_resolution}")
    if config.use_progressive_resolution:
        print(f"  {config.initial_size} → {config.final_size}")
    print("="*80 + "\n")

    # Config 저장
    config.save()

    # 모델 생성
    model = create_model(config)

    # Training
    trainer = Trainer(model, config)
    # ===================== Resume from best model =====================
    resume_from = Path("./ablation_results/TransAttUNet_run/model.pth")  # ✅ 기존 best 경로

    if resume_from.exists():
        print(f"🔁 Resuming from: {resume_from}")
        state = torch.load(resume_from, map_location=config.device, weights_only=False)

        trainer.net.load_state_dict(state["state_dict"])

        # ✅ (추천) optimizer는 새로 시작
        trainer.optimizer.load_state_dict(state["optimizer"])

        trainer.best_metric = None
        trainer.early_stop_counter = 0
        trainer.best_ckpt_metric = None

        print("✓ Model restored. Optimizer reset. Early stopping reset.")
    else:
        print("⚠️ Resume checkpoint not found. Training from scratch.")

    trainer.start()

    print(f"\nBest validation loss: {trainer.best_loss:.4f}")

    # Plot 생성
    def plot(scores, name):
        plt.figure(figsize=(15,5))
        plt.plot(range(len(scores["train"])), scores["train"], label=f'train {name}')
        plt.plot(range(len(scores["train"])), scores["val"], label=f'val {name}')
        plt.title(f'{name} plot - {config.experiment_name}')
        plt.xlabel('Epoch')
        plt.ylabel(f'{name}')
        plt.legend()
        plt.savefig(config.save_dir / f'{name}_plot.png', dpi=150, bbox_inches='tight')
        plt.close()

    plot(trainer.losses, "Loss")
    plot(trainer.dice_scores, "Dice score")
    plot(trainer.iou_scores, "IoU score")

    # Summary 저장
    summary = {
        'experiment_name': config.experiment_name,
        'fold': config.fold,
        'total_folds': config.total_folds,
        'num_epochs': config.num_epochs,
        'best_val_loss': float(trainer.best_loss),
        'final_train_loss': float(trainer.losses['train'][-1]),
        'final_val_loss': float(trainer.losses['val'][-1]),
        'final_train_dice': float(trainer.dice_scores['train'][-1]),
        'final_val_dice': float(trainer.dice_scores['val'][-1]),
        'final_train_iou': float(trainer.iou_scores['train'][-1]),
        'final_val_iou': float(trainer.iou_scores['val'][-1]),

        # Config info
        'use_dynamic_sampling': config.use_dynamic_sampling,
        'use_heavy_augmentation': config.use_heavy_augmentation,
        'use_combo_loss': config.use_combo_loss,
        'use_triplet_threshold': config.use_triplet_threshold,
        'use_progressive_training': config.use_progressive_training,
        'use_progressive_resolution': config.use_progressive_resolution,
        'backbone': config.backbone,
    }

    with open(config.save_dir / 'summary.json', 'w') as f:
        json.dump(summary, f, indent=4)

    print("\n[FINAL RESULTS]")
    print(f"Best Val Loss:     {trainer.best_loss:.4f}")
    print(f"Final Train Dice:  {trainer.dice_scores['train'][-1]:.4f}")
    print(f"Final Val Dice:    {trainer.dice_scores['val'][-1]:.4f}")
    print(f"Final Train IoU:   {trainer.iou_scores['train'][-1]:.4f}")
    print(f"Final Val IoU:     {trainer.iou_scores['val'][-1]:.4f}")

    return summary

experiments = [
    Config(
        experiment_name="TransAttUNet_run_resume",
        model_architecture="TransAttUNet",
        backbone="resnet34",
        base_lr=5e-5,
        vit_patches_size=16,
        n_skip=3,
        use_dynamic_sampling=True,
        initial_positive_ratio=0.62,
        final_positive_ratio=0.4,
        use_heavy_augmentation=True,
        use_combo_loss=True,
        bce_weight=1.0,
        dice_weight=1.0,
        focal_weight=1.0,
        use_triplet_threshold=True,
        triplet_top=0.75,
        triplet_bottom=0.3,
        triplet_min_area=2000,
        image_size=512,    # ViT/모델이 기대하는 입력 크기
        batch_size=4,
        accumulation_steps=4,
        num_epochs=40,
        use_early_stopping=True,
        early_stopping_patience=10,
        early_stopping_metric='dice',
        early_stopping_min_delta=0.1e-3,
    ),
]

all_results = []

for i, config in enumerate(experiments):
    print(f"\n{'#'*80}")
    print(f"RUNNING EXPERIMENT {i+1}/{len(experiments)}")
    print(f"{'#'*80}\n")

    try:
        result = run_experiment(config)
        all_results.append(result)
    except Exception as e:
        print(f"\n❌ Error in {config.experiment_name}: {e}")
        import traceback
        traceback.print_exc()
        continue

    print(f"\n✓ Completed {config.experiment_name}")
    print(f"{'='*80}\n")

import json
import numpy as np

def convert_to_serializable(obj):
    """NumPy types를 Python native types로 변환"""
    if isinstance(obj, dict):
        return {key: convert_to_serializable(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_to_serializable(item) for item in obj]
    elif isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj

# Test 평가 코드
test_data_folder = str(config.test_path)
test_image_files = glob.glob(os.path.join(test_data_folder, "*.png"))
test_image_ids = [os.path.basename(f).replace('.png', '').replace('.dcm', '')
                  for f in test_image_files]

train_rle_eval = pd.read_csv(str(config.rle_path))
test_ids_in_rle = [img_id for img_id in test_image_ids
                   if img_id in train_rle_eval['ImageId'].values]

print(f"\n{'='*80}")
print(f"TEST SET PREPARATION")
print(f"{'='*80}")
print(f"Total test images found: {len(test_image_ids)}")
print(f"Test images with GT in RLE: {len(test_ids_in_rle)}")
print(f"{'='*80}\n")

if len(test_ids_in_rle) > 0:

    class TestDatasetWithGT(Dataset):
        def __init__(self, image_ids, train_rle, file_mapping, size, mean, std):
            self.image_ids = image_ids
            self.train_rle = train_rle
            self.file_mapping = file_mapping
            self.size = size
            self.gb = train_rle.groupby('ImageId')

            self.transform = Compose([
                Resize(size, size),
                Normalize(mean=mean, std=std, p=1),
                ToTensorTransform(),
            ])

        def __getitem__(self, idx):
            image_id = self.image_ids[idx]

            if image_id not in self.file_mapping:
                raise FileNotFoundError(f"Image not found: {image_id}")

            image_path = self.file_mapping[image_id]
            image = cv2.imread(image_path)

            if image is None:
                raise ValueError(f"Failed to read: {image_path}")

            df = self.gb.get_group(image_id)
            annotations = df[' EncodedPixels'].tolist()

            mask = np.zeros([1024, 1024], dtype=np.float32)
            if annotations[0] != ' -1':
                for rle in annotations:
                    mask += run_length_decode(rle)
            mask = (mask >= 1).astype('float32')

            augmented = self.transform(image=image, mask=mask)
            image = augmented['image']
            mask = augmented['mask']

            if len(mask.shape) == 2:
                mask = mask.unsqueeze(0)

            return image, mask, image_id

        def __len__(self):
            return len(self.image_ids)

    # 파일 매핑 생성
    file_mapping = build_filename_mapping(
        str(config.data_path),
        str(config.test_path)
    )

    # Test dataset 및 dataloader 생성
    test_dataset = TestDatasetWithGT(
        image_ids=test_ids_in_rle,
        train_rle=train_rle_eval,
        file_mapping=file_mapping,
        size=config.image_size,
        mean=config.mean,
        std=config.std
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=True
    )

    def save_vit_attn_heatmap(attn_weights, images, save_dir, image_ids):
        """
        attn_weights: list[num_layers], each tensor (B, heads, N, N)
        images: (B, 3, H, W)  (Normalize된 상태여도 overlay는 가능)
        """
        os.makedirs(save_dir, exist_ok=True)

        last = attn_weights[-1]          # (B, heads, N, N)
        A = last.mean(dim=1)             # head 평균 -> (B, N, N)

        # token 중요도: query 축 평균 -> (B, N)
        token_score = A.mean(dim=1)      # (B, N)

        B, N = token_score.shape
        gs = int(np.sqrt(N))             # N = gs*gs 라고 가정(TransUNet config에서 그렇게 되게 맞춰둠)

        token_map = token_score.view(B, 1, gs, gs)
        token_map = F.interpolate(
            token_map,
            size=(images.shape[-2], images.shape[-1]),
            mode="bilinear",
            align_corners=False
        )
        token_map = token_map.squeeze(1).detach().cpu().numpy()  # (B, H, W)

        for i in range(B):
            hm = token_map[i]
            hm = (hm - hm.min()) / (hm.max() - hm.min() + 1e-8)
            hm_u8 = (hm * 255).astype(np.uint8)
            hm_color = cv2.applyColorMap(hm_u8, cv2.COLORMAP_JET)

            img = images[i].detach().cpu().numpy().transpose(1,2,0)
            img = (img - img.min()) / (img.max() - img.min() + 1e-8)
            img_u8 = (img * 255).astype(np.uint8)

            overlay = cv2.addWeighted(img_u8, 0.6, hm_color, 0.4, 0)
            cv2.imwrite(os.path.join(save_dir, f"{image_ids[i]}_vit_attn.png"), overlay)

    def denorm_img(img_chw, mean, std):
        """
        img_chw: torch.Tensor (3,H,W) normalized
        return: np.uint8 (H,W,3)
        """
        img = img_chw.detach().cpu().float()
        mean = torch.tensor(mean).view(3,1,1)
        std = torch.tensor(std).view(3,1,1)
        img = img * std + mean
        img = img.clamp(0, 1)
        img = (img.permute(1,2,0).numpy() * 255).astype(np.uint8)
        return img

    def save_heatmap_only(hm01, out_path, title="ViT Attention (avg over heads/tokens)"):
        """
        hm01: np.ndarray (H,W) in [0,1]
        """
        plt.figure(figsize=(6,6))
        im = plt.imshow(hm01, cmap="jet", vmin=0, vmax=1)
        plt.title(title)
        plt.axis("off")
        cbar = plt.colorbar(im, fraction=0.046, pad=0.04)
        cbar.set_label("Attention (normalized)")
        plt.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close()

    def save_overlay_with_legend(img_u8, hm01, out_path, alpha=0.4, title="Overlay + Attention Legend"):
        """
        img_u8: np.uint8 (H,W,3)
        hm01:  np.ndarray (H,W) in [0,1]
        """
        plt.figure(figsize=(6,6))
        plt.imshow(img_u8)
        im = plt.imshow(hm01, cmap="jet", vmin=0, vmax=1, alpha=alpha)
        plt.title(title)
        plt.axis("off")
        cbar = plt.colorbar(im, fraction=0.046, pad=0.04)
        cbar.set_label("Attention (normalized)")
        plt.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close()


    def evaluate_test_set(
    model,
    test_loader,
    device,
    threshold=0.5,
    save_attn=True,
    save_dir=None,
    save_max=32
):
        """
        Test set 평가 + (선택) attention 시각화 저장

        ✅ 변경점:
        - model.forward에 return_attn 인자가 있으면 (outputs, attn_weights)를 받는 방식 사용
        - 없으면 outputs만 받고 attn 저장은 자동 skip
        """
        model.eval()

        all_dice = []
        all_dice_neg = []
        all_dice_pos = []
        all_iou = []

        saved_cnt = 0
        if save_attn:
            if save_dir is None:
                save_dir = "./attn_test"
            os.makedirs(save_dir, exist_ok=True)

        # 평균 attention 누적 (저장한 샘플 기준)
        attn_sum = None
        attn_count = 0

        print(f"\n{'='*80}")
        print(f"Evaluating {len(test_loader.dataset)} test images...")
        print(f"{'='*80}")

        # return_attn 지원 여부 체크
        forward_args = model.forward.__code__.co_varnames
        supports_return_attn = ("return_attn" in forward_args)

        if save_attn and (not supports_return_attn):
            print("⚠️ This model does not support return_attn. Skipping attention visualization.")

        with torch.no_grad():
            for images, masks, image_ids in tqdm(test_loader, desc="Testing"):
                images = images.to(device)
                masks = masks.to(device)

                # ✅ 모델 출력 받기 (return_attn 지원하면 tuple)
                if supports_return_attn and save_attn:
                    out = model(images, return_attn=True)
                else:
                    out = model(images)

                if isinstance(out, tuple):
                    outputs = out[0]
                    attn_weights = out[1]
                else:
                    outputs = out
                    attn_weights = None

                probs = torch.sigmoid(outputs)

                # =========================================================
                # ✅ attention 저장 (가능한 경우에만)
                # =========================================================
                if save_attn and (attn_weights is not None) and (saved_cnt < save_max):
                    last = attn_weights[-1]  # (B, heads, N, N) or None
                    if last is not None:
                        # head 평균 -> (B, N, N)
                        A = last.mean(dim=1)
                        # token 중요도: query축 평균 -> (B, N)
                        token_score = A.mean(dim=1)

                        B, N = token_score.shape
                        gs = int(np.sqrt(N))
                        if gs * gs == N:
                            token_map = token_score.view(B, 1, gs, gs)
                            token_map = F.interpolate(
                                token_map,
                                size=(images.shape[-2], images.shape[-1]),
                                mode="bilinear",
                                align_corners=False
                            ).squeeze(1)  # (B,H,W)

                            for i in range(B):
                                if saved_cnt >= save_max:
                                    break

                                hm = token_map[i].detach().cpu().numpy()
                                hm01 = (hm - hm.min()) / (hm.max() - hm.min() + 1e-8)

                                # 평균 누적
                                if attn_sum is None:
                                    attn_sum = hm01.copy()
                                else:
                                    attn_sum += hm01
                                attn_count += 1

                                img_u8 = denorm_img(
                                    images[i],
                                    mean=getattr(test_loader.dataset, "mean", (0.485, 0.456, 0.406)),
                                    std=getattr(test_loader.dataset, "std", (0.229, 0.224, 0.225)),
                                )

                                base = os.path.join(save_dir, f"{image_ids[i]}")

                                save_heatmap_only(
                                    hm01,
                                    base + "_attn_only.png",
                                    title="Attention (no background)"
                                )

                                save_overlay_with_legend(
                                    img_u8,
                                    hm01,
                                    base + "_attn_overlay_legend.png",
                                    alpha=0.4,
                                    title="X-ray + Attention (legend)"
                                )

                                saved_cnt += 1

                # =========================================================
                # 512×512 → 1024×1024로 복원 (metric 계산용)
                # =========================================================
                probs_resized = F.interpolate(
                    probs,
                    size=(1024, 1024),
                    mode='bilinear',
                    align_corners=False
                )
                masks_resized = F.interpolate(
                    masks,
                    size=(1024, 1024),
                    mode='nearest'
                )

                dice, dice_neg, dice_pos, num_neg, num_pos = metric(
                    probs_resized, masks_resized, threshold
                )
                preds = predict(probs_resized.cpu().numpy(), threshold)
                iou = compute_iou_batch(preds, masks_resized.cpu().numpy(), classes=[1])

                all_dice.extend(dice.cpu().numpy() if torch.is_tensor(dice) else [dice])
                all_dice_neg.extend(dice_neg.cpu().numpy() if len(dice_neg) > 0 else [])
                all_dice_pos.extend(dice_pos.cpu().numpy() if len(dice_pos) > 0 else [])
                all_iou.append(iou)

        # =========================================================
        # 평균 attention 저장 (가능한 경우에만)
        # =========================================================
        if save_attn and (attn_sum is not None) and (attn_count > 0):
            avg_hm01 = attn_sum / attn_count
            save_heatmap_only(
                avg_hm01,
                os.path.join(save_dir, f"AVG_attn_only_{attn_count}.png"),
                title=f"Average Attention (n={attn_count})"
            )

        dice_mean = np.nanmean(all_dice)
        dice_neg_mean = np.nanmean(all_dice_neg) if all_dice_neg else 0.0
        dice_pos_mean = np.nanmean(all_dice_pos) if all_dice_pos else 0.0
        iou_mean = np.nanmean(all_iou)

        print(f"\n{'='*80}")
        print(f"TEST RESULTS (Threshold={threshold})")
        print(f"{'='*80}")
        print(f"Overall Dice:     {dice_mean:.4f}")
        print(f"Dice (Negative):  {dice_neg_mean:.4f}  (n={len(all_dice_neg)})")
        print(f"Dice (Positive):  {dice_pos_mean:.4f}  (n={len(all_dice_pos)})")
        print(f"IoU:              {iou_mean:.4f}")
        if save_attn and supports_return_attn:
            print(f"Saved attention visuals: {min(saved_cnt, save_max)} -> {save_dir}")
            if attn_count > 0:
                print(f"Saved average heatmap: AVG_attn_only_{attn_count}.png -> {save_dir}")
        print(f"{'='*80}\n")

        return {
            'dice': dice_mean,
            'dice_neg': dice_neg_mean,
            'dice_pos': dice_pos_mean,
            'iou': iou_mean,
            'num_samples': len(test_loader.dataset),
            'num_positive': len(all_dice_pos),
            'num_negative': len(all_dice_neg),
        }




    # 모델 로드 및 평가
    device = torch.device(config.device)
    test_model = create_model(config)  # create_model 함수 사용
    test_model = test_model.to(device)

    model_path = config.save_dir / 'model.pth'

    if not model_path.exists():
        print(f"❌ Model file not found: {model_path}")
    else:
        state = torch.load(
            str(model_path),
            map_location=device,
            weights_only=False
        )

        test_model.load_state_dict(state["state_dict"])
        test_model.eval()

        print(f"✓ Model loaded from: {model_path}")
        print(f"✓ Best validation loss: {state['best_loss']:.4f}")

        # Test set 평가
        test_results = evaluate_test_set(test_model, test_loader, device, threshold=0.5)

        # 결과 저장
        test_results_path = config.save_dir / 'test_evaluation_results.json'
        with open(test_results_path, 'w') as f:
            json.dump(convert_to_serializable(test_results), f, indent=4)

        print(f"\n✓ Test results saved to: {test_results_path}")

        # 최종 요약
        print("\n" + "="*80)
        print("FINAL TEST SUMMARY")
        print("="*80)
        print(f"Test samples:         {test_results['num_samples']}")
        print(f"Positive samples:     {test_results['num_positive']}")
        print(f"Negative samples:     {test_results['num_negative']}")
        print(f"")
        print(f"Overall Dice:         {test_results['dice']:.4f}")
        print(f"Dice (Positive):      {test_results['dice_pos']:.4f}")
        print(f"Dice (Negative):      {test_results['dice_neg']:.4f}")
        print(f"IoU:                  {test_results['iou']:.4f}")
        print("="*80)

else:
    print("⚠️ No test images with ground truth found in the RLE file.")
    print("Skipping test evaluation.")